// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// run_chisquare_test
Rcpp::List run_chisquare_test(int phenotype_length, int phen_levels_number, int genotype_num_cols, Rcpp::NumericVector phenotype_vector_r, Rcpp::NumericMatrix genotype_matrix_r, int threads);
RcppExport SEXP chi2fishercpp_run_chisquare_test(SEXP phenotype_lengthSEXP, SEXP phen_levels_numberSEXP, SEXP genotype_num_colsSEXP, SEXP phenotype_vector_rSEXP, SEXP genotype_matrix_rSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type phenotype_length(phenotype_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type phen_levels_number(phen_levels_numberSEXP);
    Rcpp::traits::input_parameter< int >::type genotype_num_cols(genotype_num_colsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type phenotype_vector_r(phenotype_vector_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type genotype_matrix_r(genotype_matrix_rSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_chisquare_test(phenotype_length, phen_levels_number, genotype_num_cols, phenotype_vector_r, genotype_matrix_r, threads));
    return rcpp_result_gen;
END_RCPP
}
